name: Update source images

on:
  schedule:
    - cron: '0 6 * * *'
  pull_request: ~
  push:
    branches:
      - master

jobs:
  update:
    name: Update source code
    runs-on: ubuntu-latest

    steps:
      - name: Fetch data
        id: fetch
        run: |
          repos=$(curl -s https://raw.githubusercontent.com/async-aws/aws/master/README.md | grep -oP '^\| \[[^!\]]+\]\(https://github\.com/async-aws/\K[^)]+')
          echo "Here are the listed repos: $repos"
          echo ::set-output name=repos::$repos

      - name: Compare & Print
        run: |
          for REPOSITORY in ${{ steps.fetch.outputs.repos }}
          do
            echo ::group::async-aws/$REPOSITORY
            rm -rf output
            git clone --branch master http://${{ secrets.BOT_GITHUB_TOKEN }}:x-oauth-basic@github.com/async-aws/$REPOSITORY/ output
            cd output
            count=$(git rev-list --count $(git describe --abbrev=0 --tags)..HEAD)
            echo "TODO, generate an SVG with '$count' and write it to $REPOSITORY.svg."
            cd ..
            echo $count
            echo ::endgroup::
          done
