name: Update source images

on:
  schedule:
    - cron: '0 6 * * *'
  pull_request: ~
  push:
    branches:
      - master

jobs:
  update:
    name: Update source code
    runs-on: ubuntu-latest

    steps:
      - name: Fetch data
        id: fetch
        run: |
          repos=$(curl -s https://raw.githubusercontent.com/async-aws/aws/master/README.md | grep -oP '^\| \[[^!\]]+\]\(https://github\.com/async-aws/\K[^)]+')
          echo "Here are the listed repos: $repos"
          echo ::set-output name=repos::$repos

      - name: Set up PHP
        uses: shivammathur/setup-php@2.1.2
        with:
          php-version: 7.4

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compare & Print
        run: |
          for REPOSITORY in ${{ steps.fetch.outputs.repos }}
          do
            echo ::group::async-aws/$REPOSITORY
            git clone --branch master https://${{ secrets.BOT_GITHUB_TOKEN }}:x-oauth-basic@github.com/async-aws/$REPOSITORY/ output
            cd output
            count=$(git rev-list --count $(git describe --abbrev=0 --tags)..HEAD)
            cd ..
            rm -rf output

            php src/image.php $REPOSITORY $count
            echo ::endgroup::
          done

      - name: View output
        run: |
          ls -l public

      - name: Commit & push the new files
        run: |
          echo "::group::git status"
          git status
          echo "::endgroup::"

          git add -N public
          if [[ $(git diff --numstat | wc -l) -eq 0 ]]; then
            echo "No changes found. Exiting."
            exit 0;
          fi

          git config --local user.email "github@async-aws.com"
          git config --local user.name "AsyncAWS Bot"

          echo "::group::git push"
          git add .
          git commit -m "Update images with new data" public/*
          git push
          echo "::endgroup::"
